name: Validate Home Assistant Add-on

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Hadolint (Dockerfile Linter)
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Validate `config.json` Exists
        run: |
          if [ -f "homeassistant-cloudflared/config.json" ]; then
            echo "✅ config.json found"
          else
            echo "❌ ERROR: config.json is missing"
            exit 1
          fi

      - name: Validate JSON Syntax
        run: |
          jq . homeassistant-cloudflared/config.json > /dev/null
          if [ $? -ne 0 ]; then
            echo "❌ ERROR: config.json contains invalid JSON syntax!"
            exit 1
          else
            echo "✅ config.json syntax is valid"
          fi

      - name: Lint Dockerfile
        run: |
          hadolint homeassistant-cloudflared/Dockerfile

      - name: Build Add-on Docker Image
        run: |
          cd homeassistant-cloudflared
          docker build -t ha-addon-test .

      - name: Test Running Container
        run: |
          docker run --rm ha-addon-test --help || echo "✅ Container runs successfully"
